version: "3.7"

services:
  database_fin_api:
    image: postgres
    container_name: database_fin_api
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: fin_api
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    links:
      - database_fin_api
    depends_on:
      - database_fin_api

volumes:
  pgdata:
    driver: local
